   PROGRAM SAX

   IMPLICIT NONE

   INTEGER, PARAMITER :: MAX_N = 4000
   REAL(8), DIMENTIONAL(MAX_N) :: SERIES
   INTEGER :: IOS , N
   REAL(8) :: X 
   
   OPEN(UNIT=67, FILE="normalized_returns.csv", STATUS ="OLD", ACTION = "READ", IOSTAT = IOS)

   IF (IOS /= 0) THEN
	PRINT*,"COULD NOT OPEN FILE"
	STOP
   END IF
   
   N = 0

   DO 
	READ(67,*,IOSTAT=IOS) X
	IF (IOS/=0) EXIT
	
	N = N + 1
	IF (N > MAX_N) THEN 
	   PRINT*, "TO MANY VALUES, VALUE LIMIT IS SET TO 4000"
	   STOP
	END IF
	SERIES(N) = X
   END DO
   CLOSE(67)
   PRINT*, "LOADED", N , "VALUES"
 
END PROGRAM SAX
